// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author            string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Commands          []string               `protobuf:"bytes,5,rep,name=commands,proto3" json:"commands,omitempty"`
	HandleAllMessages bool                   `protobuf:"varint,6,opt,name=handle_all_messages,json=handleAllMessages,proto3" json:"handle_all_messages,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_api_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *PluginInfo) GetHandleAllMessages() bool {
	if x != nil {
		return x.HandleAllMessages
	}
	return false
}

type MessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`            // 0 if private message
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // "private" or "group"
	RawMessage    string                 `protobuf:"bytes,5,opt,name=raw_message,json=rawMessage,proto3" json:"raw_message,omitempty"`
	Segments      []*MessageSegment      `protobuf:"bytes,6,rep,name=segments,proto3" json:"segments,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sender        *UserInfo              `protobuf:"bytes,8,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_api_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *MessageEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageEvent) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MessageEvent) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *MessageEvent) GetRawMessage() string {
	if x != nil {
		return x.RawMessage
	}
	return ""
}

func (x *MessageEvent) GetSegments() []*MessageSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *MessageEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageEvent) GetSender() *UserInfo {
	if x != nil {
		return x.Sender
	}
	return nil
}

type MessageSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // text, image, at, face, etc.
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSegment) Reset() {
	*x = MessageSegment{}
	mi := &file_api_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSegment) ProtoMessage() {}

func (x *MessageSegment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSegment.ProtoReflect.Descriptor instead.
func (*MessageSegment) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *MessageSegment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MessageSegment) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommandEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MessageEvent          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandEvent) Reset() {
	*x = CommandEvent{}
	mi := &file_api_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEvent) ProtoMessage() {}

func (x *CommandEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEvent.ProtoReflect.Descriptor instead.
func (*CommandEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *CommandEvent) GetMessage() *MessageEvent {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CommandEvent) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandEvent) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type HandleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handled       bool                   `protobuf:"varint,1,opt,name=handled,proto3" json:"handled,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleResult) Reset() {
	*x = HandleResult{}
	mi := &file_api_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleResult) ProtoMessage() {}

func (x *HandleResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleResult.ProtoReflect.Descriptor instead.
func (*HandleResult) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HandleResult) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

func (x *HandleResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // "private" or "group"
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Segments      []*MessageSegment      `protobuf:"bytes,4,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *SendMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendMessageRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SendMessageRequest) GetSegments() []*MessageSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_api_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SendMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_api_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Card          string                 `protobuf:"bytes,3,opt,name=card,proto3" json:"card,omitempty"` // group card name
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // owner, admin, member
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *UserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetGroupInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoRequest) Reset() {
	*x = GetGroupInfoRequest{}
	mi := &file_api_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoRequest) ProtoMessage() {}

func (x *GetGroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoRequest.ProtoReflect.Descriptor instead.
func (*GetGroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *GetGroupInfoRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	MemberCount   int32                  `protobuf:"varint,3,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_api_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *GroupInfo) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupInfo) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // debug, info, warn, error
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_api_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_plugin_proto protoreflect.FileDescriptor

const file_api_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/plugin.proto\x12\x06plugin\"\a\n" +
	"\x05Empty\"\xc0\x01\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x1a\n" +
	"\bcommands\x18\x05 \x03(\tR\bcommands\x12.\n" +
	"\x13handle_all_messages\x18\x06 \x01(\bR\x11handleAllMessages\"\xa1\x02\n" +
	"\fMessageEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12\x1f\n" +
	"\vraw_message\x18\x05 \x01(\tR\n" +
	"rawMessage\x122\n" +
	"\bsegments\x18\x06 \x03(\v2\x16.plugin.MessageSegmentR\bsegments\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12(\n" +
	"\x06sender\x18\b \x01(\v2\x10.plugin.UserInfoR\x06sender\"\x93\x01\n" +
	"\x0eMessageSegment\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x124\n" +
	"\x04data\x18\x02 \x03(\v2 .plugin.MessageSegment.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\fCommandEvent\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.plugin.MessageEventR\amessage\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\">\n" +
	"\fHandleResult\x12\x18\n" +
	"\ahandled\x18\x01 \x01(\bR\ahandled\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9f\x01\n" +
	"\x12SendMessageRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x122\n" +
	"\bsegments\x18\x04 \x03(\v2\x16.plugin.MessageSegmentR\bsegments\"J\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"g\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x12\n" +
	"\x04card\x18\x03 \x01(\tR\x04card\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"0\n" +
	"\x13GetGroupInfoRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"h\n" +
	"\tGroupInfo\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12!\n" +
	"\fmember_count\x18\x03 \x01(\x05R\vmemberCount\"<\n" +
	"\n" +
	"LogRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x8a\x02\n" +
	"\rPluginService\x12,\n" +
	"\aGetInfo\x12\r.plugin.Empty\x1a\x12.plugin.PluginInfo\x127\n" +
	"\tOnMessage\x12\x14.plugin.MessageEvent\x1a\x14.plugin.HandleResult\x127\n" +
	"\tOnCommand\x12\x14.plugin.CommandEvent\x1a\x14.plugin.HandleResult\x12/\n" +
	"\x06Health\x12\r.plugin.Empty\x1a\x16.plugin.HealthResponse\x12(\n" +
	"\bShutdown\x12\r.plugin.Empty\x1a\r.plugin.Empty2\xfb\x01\n" +
	"\n" +
	"BotService\x12F\n" +
	"\vSendMessage\x12\x1a.plugin.SendMessageRequest\x1a\x1b.plugin.SendMessageResponse\x12;\n" +
	"\vGetUserInfo\x12\x1a.plugin.GetUserInfoRequest\x1a\x10.plugin.UserInfo\x12>\n" +
	"\fGetGroupInfo\x12\x1b.plugin.GetGroupInfoRequest\x1a\x11.plugin.GroupInfo\x12(\n" +
	"\x03Log\x12\x12.plugin.LogRequest\x1a\r.plugin.EmptyB\x1eZ\x1cbot-platform/api/proto;protob\x06proto3"

var (
	file_api_proto_plugin_proto_rawDescOnce sync.Once
	file_api_proto_plugin_proto_rawDescData []byte
)

func file_api_proto_plugin_proto_rawDescGZIP() []byte {
	file_api_proto_plugin_proto_rawDescOnce.Do(func() {
		file_api_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_plugin_proto_rawDesc), len(file_api_proto_plugin_proto_rawDesc)))
	})
	return file_api_proto_plugin_proto_rawDescData
}

var file_api_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_plugin_proto_goTypes = []any{
	(*Empty)(nil),               // 0: plugin.Empty
	(*PluginInfo)(nil),          // 1: plugin.PluginInfo
	(*MessageEvent)(nil),        // 2: plugin.MessageEvent
	(*MessageSegment)(nil),      // 3: plugin.MessageSegment
	(*CommandEvent)(nil),        // 4: plugin.CommandEvent
	(*HandleResult)(nil),        // 5: plugin.HandleResult
	(*SendMessageRequest)(nil),  // 6: plugin.SendMessageRequest
	(*SendMessageResponse)(nil), // 7: plugin.SendMessageResponse
	(*GetUserInfoRequest)(nil),  // 8: plugin.GetUserInfoRequest
	(*UserInfo)(nil),            // 9: plugin.UserInfo
	(*GetGroupInfoRequest)(nil), // 10: plugin.GetGroupInfoRequest
	(*GroupInfo)(nil),           // 11: plugin.GroupInfo
	(*LogRequest)(nil),          // 12: plugin.LogRequest
	(*HealthResponse)(nil),      // 13: plugin.HealthResponse
	nil,                         // 14: plugin.MessageSegment.DataEntry
}
var file_api_proto_plugin_proto_depIdxs = []int32{
	3,  // 0: plugin.MessageEvent.segments:type_name -> plugin.MessageSegment
	9,  // 1: plugin.MessageEvent.sender:type_name -> plugin.UserInfo
	14, // 2: plugin.MessageSegment.data:type_name -> plugin.MessageSegment.DataEntry
	2,  // 3: plugin.CommandEvent.message:type_name -> plugin.MessageEvent
	3,  // 4: plugin.SendMessageRequest.segments:type_name -> plugin.MessageSegment
	0,  // 5: plugin.PluginService.GetInfo:input_type -> plugin.Empty
	2,  // 6: plugin.PluginService.OnMessage:input_type -> plugin.MessageEvent
	4,  // 7: plugin.PluginService.OnCommand:input_type -> plugin.CommandEvent
	0,  // 8: plugin.PluginService.Health:input_type -> plugin.Empty
	0,  // 9: plugin.PluginService.Shutdown:input_type -> plugin.Empty
	6,  // 10: plugin.BotService.SendMessage:input_type -> plugin.SendMessageRequest
	8,  // 11: plugin.BotService.GetUserInfo:input_type -> plugin.GetUserInfoRequest
	10, // 12: plugin.BotService.GetGroupInfo:input_type -> plugin.GetGroupInfoRequest
	12, // 13: plugin.BotService.Log:input_type -> plugin.LogRequest
	1,  // 14: plugin.PluginService.GetInfo:output_type -> plugin.PluginInfo
	5,  // 15: plugin.PluginService.OnMessage:output_type -> plugin.HandleResult
	5,  // 16: plugin.PluginService.OnCommand:output_type -> plugin.HandleResult
	13, // 17: plugin.PluginService.Health:output_type -> plugin.HealthResponse
	0,  // 18: plugin.PluginService.Shutdown:output_type -> plugin.Empty
	7,  // 19: plugin.BotService.SendMessage:output_type -> plugin.SendMessageResponse
	9,  // 20: plugin.BotService.GetUserInfo:output_type -> plugin.UserInfo
	11, // 21: plugin.BotService.GetGroupInfo:output_type -> plugin.GroupInfo
	0,  // 22: plugin.BotService.Log:output_type -> plugin.Empty
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_plugin_proto_init() }
func file_api_proto_plugin_proto_init() {
	if File_api_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_plugin_proto_rawDesc), len(file_api_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_plugin_proto_goTypes,
		DependencyIndexes: file_api_proto_plugin_proto_depIdxs,
		MessageInfos:      file_api_proto_plugin_proto_msgTypes,
	}.Build()
	File_api_proto_plugin_proto = out.File
	file_api_proto_plugin_proto_goTypes = nil
	file_api_proto_plugin_proto_depIdxs = nil
}
